version: '3'
services:
  web:
    image: captioning-service:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - redisnet
  redis:
    image: my-redis:latest
    networks:
      - redisnet
networks:
  redisnet: